#pragma config(Sensor, dgtl1,  LimitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Motor,  port1,           flashLight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           centerMotor,   tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	untilTouch(bumpSwitch);     //waits untill bump switch is pressed
	startMotor(leftMotor, -127);//Starts motor when bump is hit
	startMotor(rightMotor, -127);//Starts motor when bump is hit
	wait(5);                   //waits 100 seconds
	stopMotor(leftMotor);				 //Stops motor
	stopMotor(rightMotor,);			//Stops motor
}
