#pragma config(Sensor, dgtl1,  Start,          sensorTouch)
#pragma config(Motor,  port1,           LeftMotor,     tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           Flag,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{      
	untilButtonPress(Start);                        //waits untill button pressed to start 
	{
		if(1==1){                               //infinity loop
			motor[LeftMotor] = vexRT[Ch3];  //sets left Motor to left joystick/Ch3
			motor[RightMotor] = vexRT[Ch2]; // sets right motor to right joystick/ CH2

			if (vexRT[Btn6U] == 1)          //IF statement, if button 6u = 1
			{
				setServo(Flag, 90);     // set servo to 90
			}
			else                            //else
			{
				setServo(Flag, 0);      //set servo to 0
			}
		}
	}
}
