#pragma config(Sensor, dgtl1,  Start,          sensorTouch)
#pragma config(Motor,  port1,           LeftMotor,     tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           Flag,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	untilButtonPress(Start);
	{
		if(1==1){
			motor[LeftMotor] = vexRT[Ch3];
			motor[RightMotor] = vexRT[Ch2];

			if (vexRT[Btn6U] == 1)
			{
				setServo(Flag, 90);
			}
			else
			{
				setServo(Flag, 0);
			}
		}
	}
}
