#pragma config(Motor,	 port1,						LeftMotor,		 tmotorVex269_HBridge, openLoop, )
#pragma config(Motor,	 port2,						RightMotor,		 tmotorVex269_MC29, openLoop)
#pragma config(Motor,	 port3,						Flag,					 tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

task main()
{
	untilButtonPress(Start);
	{
		While(1==1)
		{
			if(vexRT[Btn6U] == 1)
			{
				motor[RightMotor] = 127;
			}
			else
			{
				Motor[RightMotor] = 0;
			}
		if(vexRT[Btn6D] == 1)
			{
				motor[RightMotor] = -127;
			}
			else
			{
				Motor[RightMotor] = 0;
			}
		if(vexRT[Btn5U] == 1)
			{
				motor[LeftMotor] = 127;
			}
			else
			{
				Motor[LeftMotor] = 0;
			}
			if(vexRT[Btn5D] == 1)
			{
				motor[LeftMotor] = -127;
			}
			else
			{
				Motor[LeftMotor] = 0;
			}

		}
	}
