#pragma config(Sensor, dgtl1,  startButton,    sensorTouch)
#pragma config(Motor,  port8,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftmotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	untilBump(startButton);
	startMotor(rightMotor,127);
	startMotor(leftmotor,127);
	wait(10);
	stopMotor(leftmotor);
	stopMotor(rightMotor);
	}
